# begin makefile

CFLAGS = -Wall -g

all: ex16 ex16a ex16b ex16c ex16d

clean:
	rm -f ex16
	rm -f ex16a
	rm -f ex16b
	rm -f ex16c
	rm -f ex16d
	rm -rf ex16.dSYM
	rm -rf ex16a.dSYM
	rm -rf ex16b.dSYM
	rm -rf ex16c.dSYM
	rm -rf ex16d.dSYM