# begin makefile

CFLAGS = -Wall -g

all: ex19 quicksort

ex19:
	gcc $(CFLAGS) ex19.c -o ex19

quicksort:
	gcc $(CFLAGS) quicksort.c -o quicksort

clean:
	rm -f ex19
	rm -f quicksort
	rm -rf ex19.dSYM
	rm -rf quicksort.dSYM