CFLAGS=-Wall -g

# Typical "all" make section
all: ex8

# Cleanup make section, rm's all old files
clean:
	rm -f ex8
	rm -rf ex8.dSYM

# Remake section, calls clean and all sections instead of
# using "make clean && make all" in the terminal.
remake:
	make clean
	make all