# Begin makefile

CFLAGS = -Wall -g

# We need this all section for "make" to work alone without specifying a file
all: ex11 ex11a ex11b ex11c

clean:
	rm -f ex11 ex11a ex11b ex11c 
	rm -rf ex11.dSYM ex11a.dSYM ex11b.dSYM ex11c.dSYM